import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import DemoSiteOrderForm from "@/app/components/demo/DemoSiteOrderForm";

type Locale = "ru" | "en";

export const metadata: Metadata = { title: "ALTITUDE — Extreme Expeditions", description: "Extreme and sports travel agency demo by STK Lab.", robots: { index: false, follow: false } };

const copy = {
  ru: {
    nav:["Экспедиции","Подготовка","Команда","Заявка"], eyebrow:"Экстремальные путешествия · с 2014 года", title:"Туда, где заканчиваются привычные маршруты.", text:"Высотные восхождения, джунгли, ледники и океанские экспедиции с профессиональными гидами, продуманной подготовкой и контролем риска.", cta:"Выбрать экспедицию", second:"Как мы готовим",
    tripsTitle:"Экспедиции сезона", tripsText:"Маршруты для разного уровня подготовки — от первого большого трека до серьёзной высотной программы.",
    trips:[["Базовый лагерь Эвереста","Непал · 16 дней","5 364 м","от $3 200"],["Сердце Амазонии","Бразилия · 12 дней","Джунгли","от $2 700"],["Патагония: лед и ветер","Аргентина · 11 дней","Треккинг","от $3 600"],["Килиманджаро","Танзания · 9 дней","5 895 м","от $2 900"],["Гренландия на лыжах","Арктика · 14 дней","Экспедиция","от $5 800"],["Рафтинг в Гранд-Каньоне","США · 8 дней","Класс IV","от $3 400"]],
    prepTitle:"Сила начинается с подготовки.", prepText:"До старта оцениваем опыт и форму участника, составляем план тренировок, проверяем экипировку и проводим обязательные брифинги.", prep:[["01","Оценка формы","Анкета, разговор с гидом и медицинский допуск для сложных маршрутов."],["02","План тренировок","Персональные рекомендации на 6–12 недель до выезда."],["03","Экипировка","Подробный список, проверка и помощь с арендой специального снаряжения."],["04","Безопасность","Акклиматизация, связь, спутниковый трекер и план эвакуации."]],
    stats:[["12+","лет в экспедициях"],["38","профессиональных гидов"],["27","стран и регионов"],["94%","участников достигают цели"]],
    teamTitle:"Не просто гиды. Люди, которым доверяют в сложных условиях.", teamText:"В командах — сертифицированные горные гиды, инструкторы по первой помощи, специалисты по джунглям и экспедиционные врачи.", formTitle:"Какая цель зовёт вас?", formText:"Расскажите о своём опыте и желаемом маршруте. Координатор предложит подходящий уровень и план подготовки.", demo:"Демо-сайт экспедиционной компании", back:"Travel-витрина"
  },
  en: {
    nav:["Expeditions","Preparation","Team","Apply"], eyebrow:"Extreme journeys · since 2014", title:"Beyond the edge of ordinary routes.", text:"High-altitude climbs, jungles, glaciers and ocean expeditions led by professionals, with serious preparation and disciplined risk management.", cta:"Choose an expedition", second:"How we prepare",
    tripsTitle:"This season's expeditions", tripsText:"Routes for different experience levels — from a first major trek to a serious high-altitude objective.",
    trips:[["Everest Base Camp","Nepal · 16 days","5,364 m","from $3,200"],["Heart of the Amazon","Brazil · 12 days","Jungle","from $2,700"],["Patagonia: ice and wind","Argentina · 11 days","Trekking","from $3,600"],["Kilimanjaro","Tanzania · 9 days","5,895 m","from $2,900"],["Greenland ski crossing","Arctic · 14 days","Expedition","from $5,800"],["Grand Canyon rafting","USA · 8 days","Class IV","from $3,400"]],
    prepTitle:"Strength begins with preparation.", prepText:"Before departure we assess experience and fitness, create a training plan, inspect equipment and run mandatory safety briefings.", prep:[["01","Fitness assessment","Questionnaire, guide interview and medical clearance for demanding routes."],["02","Training plan","Personal recommendations for the 6–12 weeks before departure."],["03","Equipment","Detailed list, inspection and specialist gear rental support."],["04","Safety","Acclimatization, communications, satellite tracking and evacuation plan."]],
    stats:[["12+","years of expeditions"],["38","professional guides"],["27","countries and regions"],["94%","of guests reach their objective"]],
    teamTitle:"More than guides. People you trust in demanding conditions.", teamText:"Our teams include certified mountain guides, wilderness first responders, jungle specialists and expedition doctors.", formTitle:"What objective is calling you?", formText:"Tell us about your experience and preferred route. A coordinator will recommend the right level and preparation plan.", demo:"Expedition company demo", back:"Travel collection"
  }
} as const;

export default async function ExpeditionDemo({params}:{params:Promise<{locale:string}>}) {
  const {locale:value}=await params; if(value!=="ru"&&value!=="en") notFound();
  const locale=value as Locale,t=copy[locale],other=locale==="ru"?"en":"ru";
  const tripImages=["/images/stk-lab/travel/demos/summit-hero.png","/images/stk-lab/travel/travel-digital-concierge.webp","/images/stk-lab/travel/travel-itinerary.webp","/images/stk-lab/travel/travel-trip-builder.webp","/images/stk-lab/travel/travel-bookings-operations.webp","/images/stk-lab/travel/travel-crm-dashboard.webp"];
  return <main className="min-h-screen bg-[#eef0ec] text-[#111b17]">
    <div className="bg-[#ff5a1f] px-4 py-2 text-center text-xs font-bold uppercase tracking-[.18em] text-white"><Link href={`/${locale}/industries/travel`}>{t.demo} · {t.back} →</Link><span className="mx-3">·</span><Link href={`/${locale}/demo-admin`}>{locale==="ru"?"Демо-админка":"Demo admin"} →</Link></div>
    <header className="absolute left-0 right-0 z-20 border-b border-white/20 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><Link href={`/${locale}/expedition-demo`} className="text-xl font-black tracking-[.14em]">ALTITUDE</Link><nav className="hidden gap-8 text-sm md:flex">{t.nav.map((x,i)=><a key={x} href={i===0?"#expeditions":i===1?"#preparation":i===2?"#team":"#contact"}>{x}</a>)}</nav><Link href={`/${other}/expedition-demo`} className="rounded-full border border-white/40 px-4 py-2 text-xs uppercase">{other}</Link></div></header>
    <section className="relative flex min-h-[820px] items-end overflow-hidden bg-[#07110d] text-white"><Image src="/images/stk-lab/travel/demos/summit-hero.png" alt="Himalayan expedition" fill priority className="object-cover opacity-80" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/30 to-transparent"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 pt-40 md:px-8 md:pb-32"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#ff8b5f]">{t.eyebrow}</p><h1 className="mt-6 max-w-5xl text-6xl font-black uppercase leading-[.88] tracking-[-.065em] md:text-8xl lg:text-[7.5rem]">{t.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/70">{t.text}</p><div className="mt-10 flex flex-wrap gap-3"><a href="#expeditions" className="bg-[#ff5a1f] px-7 py-4 font-bold uppercase tracking-wide">{t.cta}</a><a href="#preparation" className="border border-white/40 px-7 py-4 font-bold uppercase tracking-wide">{t.second}</a></div></div></section>
    <section className="bg-[#ff5a1f] text-white"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{t.stats.map(([n,l])=><div key={l} className="border-white/25 p-6 md:border-r md:p-8"><div className="text-4xl font-black md:text-6xl">{n}</div><p className="mt-2 text-sm text-white/75">{l}</p></div>)}</div></section>
    <section id="expeditions" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#ff5a1f]">ALTITUDE / 2026–2027</p><div className="mt-5 grid gap-6 md:grid-cols-2"><h2 className="text-5xl font-black uppercase tracking-[-.055em] md:text-7xl">{t.tripsTitle}</h2><p className="max-w-xl text-lg leading-8 text-black/55">{t.tripsText}</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{t.trips.map(([name,place,level,price],i)=><article key={name} className="overflow-hidden bg-white"><div className="relative aspect-[4/3]"><Image src={tripImages[i]} alt={name} fill className="object-cover" sizes="(max-width:1024px) 90vw, 33vw"/><span className="absolute right-4 top-4 bg-[#ff5a1f] px-3 py-2 text-xs font-bold uppercase text-white">{level}</span></div><div className="p-6"><p className="text-xs uppercase tracking-[.18em] text-black/45">{place}</p><h3 className="mt-3 text-2xl font-black uppercase">{name}</h3><div className="mt-6 flex items-center justify-between border-t border-black/10 pt-5"><b>{price}</b><span>→</span></div></div></article>)}</div></section>
    <section id="preparation" className="bg-[#111b17] text-white"><div className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><div className="grid gap-8 md:grid-cols-2"><h2 className="text-5xl font-black uppercase tracking-[-.055em] md:text-7xl">{t.prepTitle}</h2><p className="text-lg leading-8 text-white/55">{t.prepText}</p></div><div className="mt-16 grid gap-px bg-white/15 md:grid-cols-2">{t.prep.map(([n,title,text])=><div key={n} className="bg-[#111b17] p-7 md:p-9"><span className="text-[#ff6a34]">{n}</span><h3 className="mt-10 text-2xl font-black uppercase">{title}</h3><p className="mt-4 leading-7 text-white/55">{text}</p></div>)}</div></div></section>
    <section id="team" className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-24 md:grid-cols-2 md:px-8 md:py-32"><div className="relative aspect-[4/3] overflow-hidden"><Image src="/images/stk-lab/travel/travel-trip-builder.webp" alt="Expedition team" fill className="object-cover" sizes="(max-width:768px) 95vw, 50vw"/></div><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#ff5a1f]">THE TEAM</p><h2 className="mt-5 text-4xl font-black uppercase tracking-[-.05em] md:text-6xl">{t.teamTitle}</h2><p className="mt-7 text-lg leading-8 text-black/55">{t.teamText}</p></div></section>
    <section id="contact" className="bg-[#07110d] px-5 py-24 text-white md:py-32"><div className="mx-auto max-w-5xl text-center"><h2 className="text-5xl font-black uppercase tracking-[-.055em] md:text-8xl">{t.formTitle}</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/55">{t.formText}</p><DemoSiteOrderForm locale={locale} siteName="Altitude Expeditions"/></div></section>
  </main>;
}
