import Image from "next/image";
import Link from "next/link";
import StkLeadForm from "./StkLeadForm";
import TafaLabLogo from "./TafaLabLogo";
import StkSiteShell from "./design/StkSiteShell";

type Locale="ru"|"en";
const copy={
 en:{eyebrow:"Websites for entertainment & celebrations",title:"Digital experiences that begin the celebration before the doors open.",text:"Websites and booking journeys for event studios, performers, children's entertainment and family venues.",projects:"Three worlds. Three completely different reasons to celebrate.",services:[["Event & wedding website","from $800"],["Programs & packages","from $300"],["Booking journey","from $350"],["Custom event platform","Custom"]],cards:[["VELVET STAGE","Wedding and show production","/images/stk-lab/entertainment/velvet-stage-hero-v1.webp","velvet-stage-events-demo"],["SPARK!","Children's animators and party programs","/images/stk-lab/entertainment/spark-animators-hero-v1.webp","spark-animators-demo"],["WONDERNEST","Indoor play centre and birthdays","/images/stk-lab/entertainment/wondernest-kids-hero-v1.webp","wondernest-kids-demo"]],cta:"Tell us what people should feel."},
 ru:{eyebrow:"Сайты для развлечений и праздников",title:"Цифровые впечатления, с которых праздник начинается ещё до открытия дверей.",text:"Сайты и сценарии бронирования для event-студий, артистов, детских программ и семейных игровых пространств.",projects:"Три мира. Три совершенно разных повода праздновать.",services:[["Сайт событий и свадеб","от $800"],["Программы и пакеты","от $300"],["Сценарий бронирования","от $350"],["Event-платформа","Индивидуально"]],cards:[["VELVET STAGE","Проведение свадеб, шоу и частных событий","/images/stk-lab/entertainment/velvet-stage-hero-v1.webp","velvet-stage-events-demo"],["SPARK!","Аниматоры и детские праздничные программы","/images/stk-lab/entertainment/spark-animators-hero-v1.webp","spark-animators-demo"],["WONDERNEST","Игровой центр и детские дни рождения","/images/stk-lab/entertainment/wondernest-kids-hero-v1.webp","wondernest-kids-demo"]],cta:"Расскажите, что должны почувствовать гости."},
} as const;
export default function EntertainmentIndustryPage({locale}:{locale:Locale}){const t=copy[locale],other=locale==="ru"?"en":"ru";return <StkSiteShell>
 <header className="sticky top-0 z-50 border-b bg-white/85 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><Link href={`/${locale}`}><TafaLabLogo priority/></Link><nav className="hidden gap-8 text-sm md:flex"><a href="#projects">{locale==="ru"?"Проекты":"Projects"}</a><a href="#services">{locale==="ru"?"Решения":"Solutions"}</a><a href="#contact">{locale==="ru"?"Контакты":"Contact"}</a></nav><Link href={`/${other}/industries/entertainment`} className="rounded-full border px-3 py-2 text-xs uppercase">{other}</Link></div></header>
 <section className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-36"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#9a5b76]">{t.eyebrow}</p><h1 className="mt-7 max-w-6xl text-6xl leading-[.92] tracking-[-.06em] md:text-8xl">{t.title}</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-black/55">{t.text}</p><a href="#projects" className="mt-9 inline-flex rounded-full bg-black px-6 py-3.5 text-sm text-white">{locale==="ru"?"Смотреть проекты":"Explore projects"} ↓</a></section>
 <section id="projects" className="bg-[#171115] px-5 py-24 text-white md:px-8 md:py-32"><div className="mx-auto max-w-7xl"><h2 className="max-w-4xl text-5xl tracking-[-.05em] md:text-7xl">{t.projects}</h2><div className="mt-16 grid gap-5 md:grid-cols-3">{t.cards.map(([name,type,img,route],i)=><Link href={`/${locale}/${route}`} key={name} className={`${i===0?"md:translate-y-12":""} group`}><div className={`relative overflow-hidden ${i===0?"rounded-t-[7rem]":i===1?"rounded-[4rem_1rem]":"rounded-[2rem]"} aspect-[4/5]`}><Image src={img} alt={name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:768px) 95vw,33vw"/></div><p className="mt-5 text-xs uppercase tracking-[.2em] text-white/45">0{i+1}</p><h3 className="mt-2 text-3xl">{name}</h3><p className="mt-2 text-white/55">{type}</p></Link>)}</div></div></section>
 <section id="services" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><h2 className="text-5xl md:text-7xl">{locale==="ru"?"От первого афиша до последней заявки.":"From first impression to final booking."}</h2><div className="mt-14 grid border-l border-t md:grid-cols-4">{t.services.map(([name,price],i)=><div key={name} className="min-h-64 border-b border-r p-7"><span className="text-xs opacity-35">0{i+1}</span><h3 className="mt-20 text-2xl">{name}</h3><p className="mt-4 font-semibold text-[#9a5b76]">{price}</p></div>)}</div></section>
 <section id="contact" className="px-5 pb-10 md:px-8"><div className="mx-auto max-w-7xl rounded-[3rem] bg-[#171115] px-6 py-16 text-white md:px-12 md:py-24"><h2 className="max-w-4xl text-5xl md:text-7xl">{t.cta}</h2><div className="mt-10 max-w-4xl"><StkLeadForm locale={locale}/></div></div></section>
 </StkSiteShell>}
