import Link from "next/link";
import { stkLabContent, type StkLabLocale } from "./content";
import StkSiteShell from "./design/StkSiteShell";
import StkReveal from "./design/StkReveal";
import StkLeadForm from "./StkLeadForm";

const whatsapp = "https://wa.me/77471818493?text=Hello%2C%20I%27d%20like%20to%20start%20a%20conversation%20about%20a%20new%20project.";

function SectionHead({ eyebrow, title, text, dark = false }: { eyebrow: string; title: string; text: string; dark?: boolean }) {
  return <div className="mx-auto max-w-3xl text-center"><p className={`mb-4 text-xs font-semibold uppercase tracking-[0.28em] ${dark ? "text-white/45" : "text-[color:var(--stk-muted-strong)]"}`}>{eyebrow}</p><h2 className={`text-balance text-4xl font-medium tracking-[-0.04em] md:text-6xl ${dark ? "text-white" : "text-[var(--stk-text)]"}`}>{title}</h2><p className={`mx-auto mt-6 max-w-2xl text-base leading-7 md:text-lg ${dark ? "text-white/60" : "text-[color:var(--stk-muted)]"}`}>{text}</p></div>;
}

export default function StkLabHome({ locale }: { locale: StkLabLocale }) {
  const t = stkLabContent[locale];
  const other = locale === "ru" ? "en" : "ru";
  return <StkSiteShell>
    <header className="sticky top-0 z-50 border-b border-[color:var(--stk-border)] bg-[color:var(--stk-bg-translucent)] backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8">
        <Link href={`/${locale}`} className="text-lg font-semibold tracking-[-0.03em]">STK Lab</Link>
        <nav className="hidden gap-7 text-sm text-[color:var(--stk-muted-strong)] lg:flex">
          <a href="#work">{t.nav.work}</a><a href="#services">{t.nav.services}</a><a href="#process">{t.nav.process}</a><a href="#pricing">{t.nav.pricing}</a><a href="#industries">{t.nav.industries}</a><a href="#faq">{t.nav.faq}</a>
        </nav>
        <div className="flex items-center gap-3"><Link href={`/${other}`} className="rounded-full border border-[color:var(--stk-border)] px-3 py-2 text-xs uppercase">{other}</Link><a href="#contact" className="hidden rounded-full bg-[var(--stk-dark)] px-5 py-2.5 text-sm text-white sm:inline-flex" style={{ color: "#ffffff" }}>{t.nav.cta}</a></div>
      </div>
    </header>

    <section className="mx-auto grid min-h-[78vh] max-w-7xl items-center gap-12 px-5 py-20 md:px-8 lg:grid-cols-[1.1fr_.9fr] lg:py-28">
      <StkReveal><div><p className="mb-6 text-xs font-semibold uppercase tracking-[0.28em] text-[color:var(--stk-muted-strong)]">{t.hero.eyebrow}</p><h1 className="max-w-4xl text-balance text-5xl font-medium tracking-[-0.055em] md:text-7xl lg:text-[5.5rem] lg:leading-[.96]">{t.hero.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[color:var(--stk-muted)]">{t.hero.text}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-[var(--stk-dark)] px-6 py-3 text-sm text-white" style={{ color: "#ffffff" }}>{t.hero.primary}</a><a href="#work" className="rounded-full border border-[color:var(--stk-border)] px-6 py-3 text-sm">{t.hero.secondary}</a></div></div></StkReveal>
      <StkReveal delay={1}><div className="relative overflow-hidden rounded-[var(--stk-radius-card)] border border-[color:var(--stk-border)] bg-[var(--stk-media-bg)] p-6 shadow-[var(--stk-shadow-card)]"><div className="aspect-[4/5] rounded-[var(--stk-radius-panel)] bg-[radial-gradient(circle_at_70%_20%,#fff_0,transparent_28%),linear-gradient(145deg,#d8c8bd,#f8f3ed_52%,#c7aaa2)] p-6"><div className="flex h-full flex-col justify-between rounded-[var(--stk-radius-small)] border border-white/70 bg-[color:var(--stk-surface-card)] p-6 backdrop-blur"><span className="text-sm">STK Lab / Selected work</span><div><p className="text-4xl tracking-[-.05em]">Digital craft<br/>for real business.</p><p className="mt-3 max-w-xs text-sm text-[color:var(--stk-muted)]">Strategy · Design · Development · Systems</p></div></div></div></div></StkReveal>
    </section>

    <section className="border-y border-[color:var(--stk-border)] bg-[color:var(--stk-surface)]"><div className="mx-auto grid max-w-7xl grid-cols-3 px-5 md:px-8">{t.hero.stats.map(([n,l]) => <div key={l} className="py-8 text-center"><div className="text-3xl tracking-[-.04em] md:text-5xl">{n}</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-[color:var(--stk-muted-strong)]">{l}</div></div>)}</div></section>

    <section id="work" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead {...t.work}/><div className="mt-14 grid gap-5 md:grid-cols-2">{t.work.projects.map((p,i) => <Link key={p.name} href={p.href} className={`group overflow-hidden rounded-[var(--stk-radius-card)] border border-[color:var(--stk-border)] bg-[color:var(--stk-surface-card)] p-6 transition hover:-translate-y-1 hover:shadow-xl ${i===0?"md:col-span-2":""}`}><div className="mb-8 aspect-[16/8] rounded-[var(--stk-radius-small)] bg-[linear-gradient(135deg,#e7ddd4,#f8f5f0_45%,#d4b8b1)] p-6"><div className="flex h-full items-end rounded-xl border border-white/80 bg-[color:var(--stk-surface)] p-5"><span className="text-3xl tracking-[-.04em] md:text-5xl">{p.name}</span></div></div><p className="text-xs uppercase tracking-[.2em] text-[color:var(--stk-muted-strong)]">{p.type}</p><h3 className="mt-2 text-3xl tracking-[-.04em]">{p.name}</h3><p className="mt-3 max-w-2xl leading-7 text-[color:var(--stk-muted)]">{p.text}</p><div className="mt-5 flex flex-wrap gap-2">{p.tags.map(tag=><span key={tag} className="rounded-full border border-[color:var(--stk-border)] px-3 py-1 text-xs text-[color:var(--stk-muted)]">{tag}</span>)}</div></Link>)}</div></section>

    <section id="services" className="bg-[var(--stk-dark)] py-24 text-white md:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHead {...t.services} dark/><div className="mt-14 grid gap-px overflow-hidden rounded-[var(--stk-radius-card)] bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{t.services.items.map(([title,text],i)=><div key={title} className="bg-[var(--stk-dark)] p-7"><div className="text-xs text-white/40">{String(i+1).padStart(2,"0")}</div><h3 className="mt-8 text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead {...t.why}/><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{t.why.items.map(([title,text],i)=><div key={title} className="rounded-[var(--stk-radius-card)] border border-[color:var(--stk-border)] bg-[color:var(--stk-surface-card)] p-7"><div className="text-xs text-[color:var(--stk-faint)]">{String(i+1).padStart(2,"0")}</div><h3 className="mt-10 text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[color:var(--stk-muted)]">{text}</p></div>)}</div></section>

    <section id="process" className="border-y border-[color:var(--stk-border)] bg-[color:var(--stk-surface)] py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHead {...t.process}/><div className="mx-auto mt-14 max-w-4xl">{t.process.items.map(([title,text],i)=><div key={title} className="grid gap-5 border-t border-[color:var(--stk-border)] py-7 md:grid-cols-[80px_220px_1fr]"><div className="text-sm text-[color:var(--stk-faint)]">{String(i+1).padStart(2,"0")}</div><h3 className="text-xl">{title}</h3><p className="leading-7 text-[color:var(--stk-muted)]">{text}</p></div>)}</div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead {...t.pricing}/><div className="mx-auto mt-8 w-fit rounded-full border border-[color:var(--stk-border)] bg-[color:var(--stk-surface-card)] px-5 py-2 text-sm">{t.pricing.launch}</div><div className="mt-12 grid gap-4 lg:grid-cols-4">{t.pricing.plans.map(([label,name,oldPrice,price,timing,features],i)=><div key={name as string} className={`rounded-[var(--stk-radius-card)] border p-6 ${i===2?"border-[var(--stk-dark)] bg-[var(--stk-dark)] text-white":"border-[color:var(--stk-border)] bg-[color:var(--stk-surface-card)]"}`}><p className="text-xs uppercase tracking-[.2em] opacity-55">{label as string}</p><h3 className="mt-4 text-2xl">{name as string}</h3><div className="mt-8 text-sm line-through opacity-40">{oldPrice as string}</div><div className="text-3xl tracking-[-.04em]">{price as string}</div><div className="mt-2 text-xs opacity-55">{timing as string}</div><ul className="mt-8 space-y-3 text-sm leading-6">{(features as readonly string[]).map(f=><li key={f}>• {f}</li>)}</ul><a href="#contact" style={{ color: i === 2 ? "#211a17" : "#ffffff" }} className={`mt-8 inline-flex rounded-full px-5 py-2.5 text-sm font-medium ${i===2?"bg-white":"bg-[var(--stk-dark)]"}`}>{t.nav.cta}</a></div>)}</div></section>

    <section id="industries" className="bg-[var(--stk-accent-soft)] py-24 md:py-32"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHead {...t.industries}/><div className="mx-auto mt-14 grid max-w-4xl gap-px overflow-hidden rounded-[var(--stk-radius-card)] bg-black/10 sm:grid-cols-2">{t.industries.items.map((x,i)=><Link key={x.label} href={x.href} className="flex items-center justify-between bg-[var(--stk-accent-panel)] p-6 transition hover:bg-[var(--stk-accent-panel-hover)]"><span>{x.label}</span><span className="text-xs text-[color:var(--stk-muted-strong)]">{String(i+1).padStart(2,"0")} →</span></Link>)}</div></div></section>

    <section id="faq" className="mx-auto max-w-5xl px-5 py-24 md:px-8 md:py-32"><SectionHead {...t.faq}/><div className="mt-12 border-t border-[color:var(--stk-border)]">{t.faq.items.map(([q,a])=><details key={q} className="group border-b border-[color:var(--stk-border)] py-5"><summary className="cursor-pointer list-none pr-8 text-lg font-medium">{q}</summary><p className="mt-4 max-w-3xl leading-7 text-[color:var(--stk-muted)]">{a}</p></details>)}</div></section>

    <section id="contact" className="px-5 pb-10 md:px-8"><div className="mx-auto max-w-7xl rounded-[var(--stk-radius-card)] bg-[var(--stk-dark)] px-6 py-20 text-center text-white md:px-12 md:py-28"><p className="text-xs uppercase tracking-[.25em] text-white/45">{t.cta.eyebrow}</p><h2 className="mx-auto mt-4 max-w-4xl text-balance text-4xl tracking-[-.05em] md:text-7xl">{t.cta.title}</h2><p className="mx-auto mt-6 max-w-2xl leading-7 text-white/60">{t.cta.text}</p><div className="mx-auto mt-10 max-w-3xl text-left"><StkLeadForm locale={locale}/></div><div className="mt-5 flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-xs text-white/45"><span>{t.cta.note}</span><a href={whatsapp} target="_blank" rel="noreferrer" className="underline decoration-white/25 underline-offset-4 hover:text-white" style={{color:"inherit"}}>{locale==="ru"?"Или написать в WhatsApp":"Or message us on WhatsApp"} ↗</a></div></div></section>

    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm text-[color:var(--stk-muted-strong)] md:flex-row md:items-center md:justify-between md:px-8"><span className="font-medium text-[var(--stk-text)]">STK Lab</span><span>{t.footer}</span><span>© {new Date().getFullYear()}</span></footer>
  </StkSiteShell>;
}