import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import DemoSiteOrderForm from "@/app/components/demo/DemoSiteOrderForm";

type Locale="ru"|"en";
export const metadata:Metadata={title:"MILEWISE — Travel Hacking Academy",description:"Travel hacking education platform demo by STK Lab.",robots:{index:false,follow:false}};
const copy={
 ru:{nav:["Программа","Результаты","Тарифы","Заявка"],eyebrow:"Онлайн-школа разумных путешествий",title:"Летайте дальше. Платите меньше.",text:"Научитесь находить сильные тарифы, использовать мили и бонусные программы и собирать сложные маршруты без переплаты.",cta:"Выбрать программу",secondary:"Бесплатный урок",proof:"Практика, а не теория",proofText:"Работаем на реальных поисковых сценариях: от первого билета за мили до кругосветного маршрута с несколькими программами лояльности.",modules:[["01","Поиск авиабилетов","Гибкие даты, соседние аэропорты, open jaw и скрытые возможности сложных маршрутов."],["02","Мили и баллы","Как выбирать программы, накапливать бонусы и считать реальную ценность мили."],["03","Отели и статусы","Кэшбэк, бесплатные ночи, апгрейды и преимущества гостиничных программ."],["04","Сложные маршруты","Stopover, multi-city, позиционирующие перелёты и защита стыковок."],["05","Инструменты","Сервисы поиска премиальных мест, уведомления и личная система контроля."],["06","Безопасность","Правила тарифов, визы, страховка, возвраты и риски, о которых важно знать."]],results:[["−42%","средняя экономия учеников на первых маршрутах"],["18","пошаговых уроков"],["12","практических заданий"],["6 недель","доступа к проверке домашних работ"]],cases:[["Бизнес-класс в Токио","1 850 $ → 620 $ + мили"],["Три страны Европы","980 $ → 540 $"],["Бали на Новый год","1 240 $ → 760 $"]],plans:[["Start","Самостоятельно","$79","18 уроков, шаблоны и доступ на 3 месяца"],["Practice","С куратором","$189","Проверка заданий, чат и разбор вашего маршрута"],["Pro","Личная стратегия","$390","Индивидуальная сессия и персональная система миль"]],formTitle:"Начните с вашего следующего маршрута.",formText:"Оставьте заявку — подберём формат обучения и покажем, где именно вы переплачиваете сейчас.",demo:"Демо-сайт школы travel hacking",back:"Travel-витрина"},
 en:{nav:["Curriculum","Results","Plans","Apply"],eyebrow:"The online school for smarter travel",title:"Fly farther. Spend less.",text:"Learn to find powerful fares, use miles and loyalty programs, and build complex itineraries without overpaying.",cta:"Choose a program",secondary:"Free lesson",proof:"Practice, not theory",proofText:"Work through real search scenarios — from a first points booking to a round-the-world itinerary involving multiple loyalty programs.",modules:[["01","Flight search","Flexible dates, nearby airports, open jaws and the hidden potential of complex routes."],["02","Miles and points","How to choose programs, earn rewards and calculate the true value of a mile."],["03","Hotels and status","Cashback, free nights, upgrades and useful hotel loyalty benefits."],["04","Complex itineraries","Stopovers, multi-city tickets, positioning flights and connection protection."],["05","Tools","Award search services, alerts and a personal tracking system."],["06","Travel safely","Fare rules, visas, insurance, refunds and the risks worth understanding."]],results:[["−42%","average saving on students' first routes"],["18","step-by-step lessons"],["12","practical assignments"],["6 weeks","of reviewed coursework"]],cases:[["Business class to Tokyo","$1,850 → $620 + miles"],["Three countries in Europe","$980 → $540"],["Bali for New Year","$1,240 → $760"]],plans:[["Start","Self-paced","$79","18 lessons, templates and 3-month access"],["Practice","With a mentor","$189","Assignment reviews, chat and your itinerary audit"],["Pro","Personal strategy","$390","Private session and your own points system"]],formTitle:"Start with your next journey.",formText:"Send a request and we will recommend the right learning format and show where you may be overpaying today.",demo:"Travel hacking academy demo",back:"Travel collection"}
} as const;

export default async function TravelHackingDemo({params}:{params:Promise<{locale:string}>}){const{locale:value}=await params;if(value!=="ru"&&value!=="en")notFound();const locale=value as Locale,t=copy[locale],other=locale==="ru"?"en":"ru";return <main className="min-h-screen bg-[#f5f1e8] text-[#0a1c3a]">
 <div className="bg-[#ff6b55] px-4 py-2 text-center text-xs font-bold text-white"><Link href={`/${locale}/industries/travel`}>{t.demo} · {t.back} →</Link><span className="mx-3">·</span><Link href={`/${locale}/demo-admin`}>{locale==="ru"?"Демо-админка":"Demo admin"} →</Link></div>
 <header className="absolute left-0 right-0 z-20 border-b border-white/15 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><Link href={`/${locale}/travel-hacking-demo`} className="text-xl font-black">MILE<span className="text-[#ff7a63]">WISE</span></Link><nav className="hidden gap-8 text-sm md:flex">{t.nav.map((x,i)=><a key={x} href={i===0?"#curriculum":i===1?"#results":i===2?"#plans":"#contact"}>{x}</a>)}</nav><Link href={`/${other}/travel-hacking-demo`} className="rounded-full border border-white/35 px-4 py-2 text-xs uppercase">{other}</Link></div></header>
 <section className="relative flex min-h-[780px] items-center overflow-hidden bg-[#06152f] bg-cover bg-center bg-no-repeat text-white" style={{backgroundImage:'url("/images/stk-lab/travel/milewise/milewise-hero.webp")'}}><div className="absolute inset-0 bg-gradient-to-r from-[#06152f]/95 via-[#06152f]/70 to-[#06152f]/10"/><div className="relative mx-auto w-full max-w-7xl px-5 pb-20 pt-36 md:px-8"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#ff8a76]">{t.eyebrow}</p><h1 className="mt-6 max-w-4xl text-6xl font-black leading-[.92] tracking-[-.065em] md:text-8xl lg:text-[7rem]">{t.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">{t.text}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#plans" className="rounded-full bg-[#ff6b55] px-7 py-4 font-bold">{t.cta}</a><a href="#curriculum" className="rounded-full border border-white/30 px-7 py-4">{t.secondary}</a></div></div></section>
 <section className="bg-[#3c65ff] text-white"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{t.results.map(([n,l])=><div key={l} className="p-6 md:p-8"><div className="text-4xl font-black md:text-5xl">{n}</div><p className="mt-2 text-sm text-white/70">{l}</p></div>)}</div></section>
 <section className="mx-auto grid max-w-7xl gap-4 px-5 pt-24 md:grid-cols-3 md:px-8"><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image src="/images/stk-lab/travel/milewise/flight-search-class.webp" alt="Travel hacking flight search class" fill className="object-cover" sizes="(max-width:768px) 95vw, 33vw"/></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image src="/images/stk-lab/travel/milewise/miles-points.webp" alt="Miles and points planning" fill className="object-cover" sizes="(max-width:768px) 95vw, 33vw"/></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image src="/images/stk-lab/travel/milewise/mentor-session.webp" alt="Online session with a travel mentor" fill className="object-cover" sizes="(max-width:768px) 95vw, 33vw"/></div></section>
 <section id="curriculum" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><div className="grid gap-8 md:grid-cols-2"><h2 className="text-5xl font-black tracking-[-.055em] md:text-7xl">{t.proof}</h2><p className="text-lg leading-8 text-black/55">{t.proofText}</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{t.modules.map(([n,title,text])=><article key={n} className="rounded-[2rem] border border-black/10 bg-white p-7"><span className="font-black text-[#3c65ff]">{n}</span><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-4 leading-7 text-black/55">{text}</p></article>)}</div></section>
 <section className="bg-[#091c3c] px-5 pt-24 md:px-8"><div className="relative mx-auto aspect-[16/7] max-w-7xl overflow-hidden rounded-[2rem]"><Image src="/images/stk-lab/travel/milewise/student-route-result.webp" alt="Student travel route result" fill className="object-cover" sizes="100vw"/></div></section>
 <section id="results" className="bg-[#091c3c] text-white"><div className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#ff7a63]">REAL ROUTE EXAMPLES</p><h2 className="mt-5 max-w-4xl text-5xl font-black tracking-[-.055em] md:text-7xl">{locale==="ru"?"Экономия, которую можно посчитать.":"Savings you can actually measure."}</h2><div className="mt-14 grid gap-4 md:grid-cols-3">{t.cases.map(([route,result],i)=><div key={route} className="rounded-[2rem] bg-white/8 p-7"><span className="text-white/30">0{i+1}</span><h3 className="mt-14 text-2xl font-bold">{route}</h3><p className="mt-4 text-lg text-[#79a0ff]">{result}</p></div>)}</div></div></section>
 <section id="plans" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#3c65ff]">{locale==="ru"?"Форматы обучения":"Learning plans"}</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] md:text-7xl">{locale==="ru"?"Выберите свой темп.":"Choose your pace."}</h2><div className="mt-14 grid gap-5 lg:grid-cols-3">{t.plans.map(([name,mode,price,text],i)=><article key={name} className={`rounded-[2rem] p-8 ${i===1?"bg-[#3c65ff] text-white":"border border-black/10 bg-white"}`}><p className="text-sm opacity-60">{mode}</p><h3 className="mt-7 text-3xl font-black">{name}</h3><div className="mt-5 text-5xl font-black">{price}</div><p className={`mt-6 leading-7 ${i===1?"text-white/65":"text-black/55"}`}>{text}</p><a href="#contact" className={`mt-10 inline-flex rounded-full px-6 py-3 font-bold ${i===1?"bg-white text-[#3c65ff]":"bg-[#091c3c] text-white"}`}>{locale==="ru"?"Записаться":"Enroll"}</a></article>)}</div></section>
 <section id="contact" className="bg-[#06152f] px-5 py-24 text-white md:py-32"><div className="mx-auto max-w-5xl text-center"><h2 className="text-5xl font-black tracking-[-.055em] md:text-8xl">{t.formTitle}</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/55">{t.formText}</p><DemoSiteOrderForm locale={locale} siteName="Milewise Travel Hacking Academy" kind="academy"/></div></section>
 </main>}
