"use client";
import { useEffect, useMemo, useState } from "react";
import { useLocale } from "next-intl";
import { supabase } from "@/lib/supabase";
type Stage="new"|"contacted"|"proposal"|"won"|"lost";
type Order={id:string;order_number:number|null;created_at:string;status:string;customer_name:string|null;customer_email:string|null;customer_phone:string|null;customer_comment:string|null;price:number|string|null};
type Meta={stage:Stage;note:string;followUp:string};
const blank:Meta={stage:"new",note:"",followUp:""};
export default function AdminCrmPage(){
 const ru=useLocale()!=="en"; const [orders,setOrders]=useState<Order[]>([]); const [id,setId]=useState<string|null>(null); const [q,setQ]=useState(""); const [filter,setFilter]=useState<Stage|"all">("all"); const [meta,setMeta]=useState<Record<string,Meta>>({}); const [loading,setLoading]=useState(true);
 useEffect(()=>{try{setMeta(JSON.parse(localStorage.getItem("tafa-admin-crm")||"{}"));}catch{} void(async()=>{const {data}=await supabase.from("orders").select("id,order_number,created_at,status,customer_name,customer_email,customer_phone,customer_comment,price").neq("weight","DEMO_SITE_ORDER").order("created_at",{ascending:false});const x=(data||[]) as Order[];setOrders(x);setId(x[0]?.id||null);setLoading(false)})();},[]);
 const labels:Record<Stage,string>=ru?{new:"Новая",contacted:"Связались",proposal:"Предложение",won:"Клиент",lost:"Неактуально"}:{new:"New",contacted:"Contacted",proposal:"Proposal",won:"Won",lost:"Lost"};
 const list=useMemo(()=>orders.filter(o=>{const value=[o.customer_name,o.customer_email,o.customer_phone,String(o.order_number||"")].join(" ").toLowerCase();return value.includes(q.toLowerCase())&&(filter==="all"||(meta[o.id]?.stage||"new")===filter)}),[orders,q,filter,meta]);
 const selected=orders.find(o=>o.id===id)||list[0]||null; const m=selected?{...blank,...(meta[selected.id]||{})}:blank;
 function save(p:Partial<Meta>){if(!selected)return;const next={...meta,[selected.id]:{...m,...p}};setMeta(next);localStorage.setItem("tafa-admin-crm",JSON.stringify(next));}
 return <div className="admin-page"><section className="admin-page-heading"><div><span className="admin-eyebrow">{ru?"Клиенты и заявки":"Clients and leads"}</span><h1>CRM</h1><p>{ru?"Заявки с сайтов, этапы, заметки и следующие контакты.":"Website requests, stages, notes and follow-ups."}</p></div><div className="rounded-full bg-[#f3e9e3] px-4 py-3 text-sm font-semibold">{list.length} {ru?"заявок":"leads"}</div></section><section className="grid gap-6 xl:grid-cols-[420px_1fr]"><div className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b border-black/5 p-5"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ru?"Поиск по имени, телефону или email":"Search name, phone or email"} className="w-full rounded-2xl border border-black/10 px-4 py-3"/><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setFilter("all")} className={"rounded-full px-3 py-2 text-xs "+(filter==="all"?"bg-[#3d2923] text-white":"bg-[#f5efeb]")}>{ru?"Все":"All"}</button>{(Object.keys(labels) as Stage[]).map(x=><button key={x} onClick={()=>setFilter(x)} className={"rounded-full px-3 py-2 text-xs "+(filter===x?"bg-[#3d2923] text-white":"bg-[#f5efeb]")}>{labels[x]}</button>)}</div></div><div className="max-h-[680px] overflow-y-auto">{loading?<p className="p-6 text-black/50">{ru?"Загрузка...":"Loading..."}</p>:list.map(o=><button key={o.id} onClick={()=>setId(o.id)} className={"block w-full border-b border-black/5 p-5 text-left "+(selected?.id===o.id?"bg-[#f3e9e3]":"hover:bg-[#faf7f5]")}><div className="flex justify-between gap-3"><strong>{o.customer_name|| (ru?"Без имени":"Unnamed")}</strong><span className="text-xs text-black/40">#{o.order_number||o.id.slice(0,6)}</span></div><p className="mt-1 text-sm text-black/50">{o.customer_email||o.customer_phone||"—"}</p><span className="mt-3 inline-flex rounded-full bg-[#ead8cc] px-2 py-1 text-xs">{labels[meta[o.id]?.stage||"new"]}</span></button>)}</div></div>{selected?<ClientCard ru={ru} order={selected} meta={m} labels={labels} save={save}/>:<div className="rounded-3xl bg-white p-8">{ru?"Выберите заявку":"Select a lead"}</div>}</section></div>;
}
function ClientCard({ru,order,meta,labels,save}:{ru:boolean;order:Order;meta:Meta;labels:Record<Stage,string>;save:(x:Partial<Meta>)=>void}){
 const [saving,setSaving]=useState(false);
 async function change(stage:Stage){save({stage});setSaving(true);await supabase.from("orders").update({status:stage==="won"?"completed":stage==="lost"?"cancelled":stage==="new"?"new":"in_progress"}).eq("id",order.id);setSaving(false);}
 return <div className="rounded-3xl bg-white p-6 shadow-sm md:p-8"><span className="text-xs uppercase tracking-[.2em] text-black/40">{ru?"Карточка клиента":"Client card"}</span><h2 className="mt-2 text-3xl font-semibold">{order.customer_name|| (ru?"Без имени":"Unnamed")}</h2><div className="mt-7 grid gap-3 sm:grid-cols-3"><a className="rounded-2xl bg-[#faf7f5] p-4" href={order.customer_phone?"tel:"+order.customer_phone:undefined}><small className="block text-black/40">{ru?"Телефон":"Phone"}</small><strong>{order.customer_phone||"—"}</strong></a><a className="rounded-2xl bg-[#faf7f5] p-4" href={order.customer_email?"mailto:"+order.customer_email:undefined}><small className="block text-black/40">Email</small><strong className="break-all">{order.customer_email||"—"}</strong></a><div className="rounded-2xl bg-[#faf7f5] p-4"><small className="block text-black/40">{ru?"Сумма":"Amount"}</small><strong>{"$"+Math.round(Number(order.price||0))}</strong></div></div><div className="mt-8"><b>{ru?"Этап сделки":"Deal stage"}</b><div className="mt-3 flex flex-wrap gap-2">{(Object.keys(labels) as Stage[]).map(x=><button disabled={saving} key={x} onClick={()=>void change(x)} className={"rounded-full border px-4 py-2 text-sm "+(meta.stage===x?"border-[#3d2923] bg-[#3d2923] text-white":"border-black/10")}>{labels[x]}</button>)}</div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><label><span className="text-sm font-semibold">{ru?"Внутренняя заметка":"Internal note"}</span><textarea value={meta.note} onChange={e=>save({note:e.target.value})} placeholder={ru?"Например: отправить предложение в понедельник":"Example: send proposal on Monday"} className="mt-3 min-h-36 w-full rounded-2xl border border-black/10 p-4"/></label><label><span className="text-sm font-semibold">{ru?"Следующий контакт":"Next follow-up"}</span><input type="date" value={meta.followUp} onChange={e=>save({followUp:e.target.value})} className="mt-3 w-full rounded-2xl border border-black/10 p-4"/><p className="mt-3 text-sm text-black/45">{ru?"Сохраняется в CRM этого браузера.":"Saved in this browser's CRM."}</p></label></div>{order.customer_comment&&<div className="mt-6 rounded-2xl bg-[#faf7f5] p-4"><small className="block text-black/40">{ru?"Комментарий из заявки":"Request comment"}</small><p className="mt-2 whitespace-pre-wrap">{order.customer_comment}</p></div>}</div>;
}
