import Image from "next/image";
import Link from "next/link";

import DemoSiteOrderForm from "./DemoSiteOrderForm";

type Locale = "ru" | "en";
type Kind = "veloura" | "levain" | "eclair";

const data = {
  veloura: {
    brand: "VELOURA CAKES",
    route: "veloura-cakes-demo",
    hero: "/images/stk-lab/bakery/veloura-cakes.webp",
    feature: "/images/stk-lab/bakery/cake-builder.webp",
    bg: "#f6eceb", ink: "#4a292f", accent: "#b86b78", soft: "#ead7d9",
    en: { label:"Bespoke cake atelier · made to order", title:"A celebration, designed around you.", text:"Sculptural cakes, delicate finishes and a calm digital journey from first inspiration to final order.", cta:"Create your cake", collection:"Signature creations", story:"Crafted as a centrepiece", storyText:"Every cake begins with the occasion, then develops through flavour, scale, colour and hand-finished detail.", stats:[["48 h","design reply"],["18","signature flavours"],["100%","made by hand"]], items:[["Silk Rose","vanilla, raspberry, white chocolate","from $120"],["Pearl Garden","pistachio, cherry, mascarpone","from $145"],["Ivory Bloom","lemon, elderflower, cream","from $130"],["Midnight Bow","dark chocolate, hazelnut, coffee","from $155"]], form:"Begin your cake story", formText:"Share the date, number of guests and the atmosphere you want to create." },
    ru: { label:"Авторское ателье тортов · на заказ", title:"Праздник, созданный вокруг вас.", text:"Скульптурные торты, тонкая отделка и спокойный путь от первого вдохновения до готового заказа.", cta:"Создать свой торт", collection:"Авторская коллекция", story:"Главный акцент праздника", storyText:"Каждый торт начинается с события, а затем обретает вкус, масштаб, цвет и детали ручной работы.", stats:[["48 ч","ответ по дизайну"],["18","авторских вкусов"],["100%","ручная работа"]], items:[["Silk Rose","ваниль, малина, белый шоколад","от $120"],["Pearl Garden","фисташка, вишня, маскарпоне","от $145"],["Ivory Bloom","лимон, бузина, сливки","от $130"],["Midnight Bow","тёмный шоколад, фундук, кофе","от $155"]], form:"Начните историю вашего торта", formText:"Расскажите о дате, количестве гостей и атмосфере, которую хотите создать." },
  },
  levain: {
    brand: "MAISON LEVAIN",
    route: "maison-levain-demo",
    hero: "/images/stk-lab/bakery/maison-sucre.webp",
    feature: "/images/stk-lab/bakery/bakery-products.webp",
    bg: "#efe8dc", ink: "#3a3025", accent: "#9a6a3a", soft: "#dfd2be",
    en: { label:"Artisan bakery · naturally leavened", title:"Bread made slowly. Mornings made better.", text:"A neighbourhood bakery devoted to natural fermentation, local grain and warm bread throughout the day.", cta:"Pre-order for tomorrow", collection:"From the ovens", story:"Flour, water, salt and time", storyText:"Long fermentation builds flavour naturally. Every loaf is mixed, folded and baked by hand in small daily batches.", stats:[["36 h","fermentation"],["4","local grains"],["7:00","first bake"]], items:[["Country sourdough","wheat, rye, sea salt","$8"],["Seeded levain","sunflower, flax, sesame","$10"],["Butter croissant","cultured butter, crisp layers","$4"],["Morning brioche","vanilla, orange zest","$6"]], form:"Reserve your bake", formText:"Choose what you would like us to hold and your preferred collection time." },
    ru: { label:"Ремесленная пекарня · натуральная закваска", title:"Хлеб, которому дали время. Утро, которое стало лучше.", text:"Соседская пекарня с натуральной ферментацией, локальным зерном и свежей выпечкой в течение дня.", cta:"Предзаказ на завтра", collection:"Из наших печей", story:"Мука, вода, соль и время", storyText:"Долгая ферментация естественно раскрывает вкус. Каждый хлеб замешивается, складывается и выпекается вручную небольшими партиями.", stats:[["36 ч","ферментации"],["4","локальных зерна"],["7:00","первая выпечка"]], items:[["Деревенский sourdough","пшеница, рожь, морская соль","$8"],["Зерновой levain","подсолнечник, лён, кунжут","$10"],["Круассан на сливочном масле","хрустящие воздушные слои","$4"],["Утренняя бриошь","ваниль, цедра апельсина","$6"]], form:"Забронируйте свежую выпечку", formText:"Выберите продукты и удобное время получения заказа." },
  },
  eclair: {
    brand: "ÉCLAIR MAISON",
    route: "eclair-maison-demo",
    hero: "/images/stk-lab/bakery/bakery-online-store.webp",
    feature: "/images/stk-lab/bakery/bakery-delivery.webp",
    bg: "#f7f4ed", ink: "#20201e", accent: "#c5a260", soft: "#e8e1d3",
    en: { label:"French pâtisserie · Parisian delivery", title:"Small works of pastry, delivered beautifully.", text:"A modern online pâtisserie for éclairs, petits gâteaux and elegant gift boxes prepared for every occasion.", cta:"Shop the collection", collection:"The maison selection", story:"Parisian precision, modern ease", storyText:"Classic French technique meets online ordering, scheduled delivery and gift-ready presentation.", stats:[["12","daily pastries"],["90 min","city delivery"],["6","gift collections"]], items:[["Vanilla Éclair","Madagascar vanilla, choux","$9"],["Noisette","hazelnut praline, milk chocolate","$10"],["Citron","lemon cream, meringue","$9"],["Maison Box","six seasonal pastries","$52"]], form:"Order from the maison", formText:"Tell us what you need, the delivery date and whether it is a gift." },
    ru: { label:"Французская pâtisserie · доставка", title:"Маленькие произведения, доставленные красиво.", text:"Современная онлайн-кондитерская с эклерами, petits gâteaux и элегантными подарочными наборами для любого события.", cta:"Открыть коллекцию", collection:"Коллекция maison", story:"Парижская точность и современное удобство", storyText:"Классическая французская техника сочетается с онлайн-заказом, доставкой ко времени и подарочной подачей.", stats:[["12","десертов ежедневно"],["90 мин","доставка по городу"],["6","подарочных коллекций"]], items:[["Vanilla Éclair","мадагаскарская ваниль, заварное тесто","$9"],["Noisette","фундучное пралине, молочный шоколад","$10"],["Citron","лимонный крем, меренга","$9"],["Maison Box","шесть сезонных десертов","$52"]], form:"Заказ из maison", formText:"Укажите, что вам нужно, дату доставки и будет ли это подарком." },
  },
} as const;

export default function BakeryDemoPage({ locale, kind }: { locale: Locale; kind: Kind }) {
  const item = data[kind];
  const t = item[locale];
  const other = locale === "ru" ? "en" : "ru";
  return <main style={{background:item.bg,color:item.ink}} className="min-h-screen">
    <div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-1 px-4 py-2 text-center text-[11px] uppercase tracking-[.18em] opacity-75"><span>{locale==="ru"?"Демо-пекарня · создано Tafa Lab":"Demo bakery · created by Tafa Lab"}</span><Link className="underline underline-offset-4" href={`/${locale}/industries/bakeries`}>{locale==="ru"?"Все проекты":"All bakery projects"} →</Link><Link className="underline underline-offset-4" href={`/${locale}/demo-admin`}>{locale==="ru"?"Демо-админка":"Demo admin"} →</Link></div>
    <header className="flex items-center justify-between border-y px-5 py-5 md:px-10" style={{borderColor:`${item.ink}22`}}><div className="font-serif text-xl tracking-[.14em] md:text-2xl">{item.brand}</div><nav className="hidden gap-8 text-sm md:flex"><a href="#collection">{locale==="ru"?"Коллекция":"Collection"}</a><a href="#story">{locale==="ru"?"О бренде":"Story"}</a><a href="#order">{locale==="ru"?"Заказать":"Order"}</a></nav><Link href={`/${other}/${item.route}`} className="rounded-full border px-4 py-2 text-xs uppercase" style={{borderColor:`${item.ink}44`}}>{other}</Link></header>
    <section className="relative min-h-[720px] overflow-hidden bg-cover bg-center" style={{backgroundImage:`linear-gradient(90deg, rgba(25,18,16,.82), rgba(25,18,16,.2) 65%), url(${item.hero})`}}><div className="mx-auto flex min-h-[720px] max-w-7xl items-end px-5 pb-16 text-white md:px-10 md:pb-24"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.3em]" style={{color:item.accent}}>{t.label}</p><h1 className="mt-7 font-serif text-6xl leading-[.92] tracking-[-.055em] md:text-8xl lg:text-[7rem]">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/75 md:text-xl">{t.text}</p><a href="#order" className="mt-9 inline-flex rounded-full px-7 py-4 font-semibold" style={{background:item.accent,color:item.ink}}>{t.cta} →</a></div></div></section>
    <section id="story" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 md:grid-cols-[1.1fr_.9fr] md:px-10 md:py-32"><div><p className="text-xs uppercase tracking-[.3em] opacity-50">{locale==="ru"?"Наша история":"Our story"}</p><h2 className="mt-5 font-serif text-5xl tracking-[-.05em] md:text-7xl">{t.story}</h2><p className="mt-7 max-w-2xl text-xl leading-9 opacity-65">{t.storyText}</p></div><div className="grid grid-cols-3 self-end border-y py-8" style={{borderColor:`${item.ink}33`}}>{t.stats.map(([n,l])=><div key={l} className="px-3 text-center"><div className="text-3xl font-semibold md:text-4xl" style={{color:item.accent}}>{n}</div><div className="mt-2 text-xs leading-5 opacity-55">{l}</div></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 pb-24 md:px-10 md:pb-32"><div className="relative aspect-[3/2] overflow-hidden rounded-[2rem]"><Image src={item.feature} alt={item.brand} fill className="object-cover" sizes="(max-width:768px) 95vw, 1200px"/></div></section>
    <section id="collection" className="px-5 py-24 md:px-10 md:py-32" style={{background:item.soft}}><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.3em] opacity-50">{locale==="ru"?"Выбор редакции":"Curated selection"}</p><h2 className="mt-4 font-serif text-5xl tracking-[-.05em] md:text-7xl">{t.collection}</h2><div className="mt-14 grid gap-x-12 md:grid-cols-2">{t.items.map(([name,desc,price],i)=><article key={name} className="grid grid-cols-[42px_1fr_auto] gap-4 border-t py-7" style={{borderColor:`${item.ink}28`}}><span className="text-xs opacity-35">0{i+1}</span><div><h3 className="text-xl font-semibold">{name}</h3><p className="mt-2 text-sm opacity-55">{desc}</p></div><strong style={{color:item.accent}}>{price}</strong></article>)}</div></div></section>
    <section id="order" className="px-5 py-24 text-white md:px-10 md:py-32" style={{background:item.ink}}><div className="mx-auto max-w-5xl text-center"><p className="text-xs uppercase tracking-[.3em] text-white/45">{locale==="ru"?"Онлайн-заказ · демо":"Online order · demo"}</p><h2 className="mt-5 font-serif text-5xl tracking-[-.05em] md:text-7xl">{t.form}</h2><p className="mx-auto mt-5 max-w-xl text-lg text-white/60">{t.formText}</p><DemoSiteOrderForm locale={locale} siteName={`${item.brand} — bakery order`} kind="bakery"/></div></section>
    <footer className="flex flex-col gap-3 px-5 py-8 text-xs opacity-60 md:flex-row md:justify-between md:px-10"><span>© 2026 {item.brand}</span><span>{locale==="ru"?"Демонстрационный сайт Tafa Lab":"A demonstration website by Tafa Lab"}</span></footer>
  </main>;
}
