import Link from "next/link";

import DemoSiteOrderForm from "./DemoSiteOrderForm";

type Locale = "ru" | "en";
type Kind = "operations" | "inventory" | "workforce" | "finance";

const platforms = {
  operations: {
    brand:"NEXUS / ONE", route:"operations-platform-demo", image:"/images/stk-lab/business-platforms/demos/nexus-operations.png", bg:"#07152f", ink:"#f4f8ff", accent:"#3a7cff", soft:"#0d2250", radius:"rounded-2xl",
    en:{tag:"Multi-branch operations cloud",title:"Every branch. One live picture.",text:"Orders, stock, teams and decisions connected in one command centre for growing multi-location businesses.",cta:"Explore the system",section:"The operating layer for your whole network",sectionText:"Owners see the company. Managers see their branch. Teams see exactly what needs action now.",metrics:[["24","active branches"],["8,347","orders this month"],["12.6%","revenue growth"]],modules:[["Live operations","Orders, statuses and branch workload in real time."],["Branch control","Separate access, targets and performance for every location."],["Inventory alerts","Critical stock levels and transfers without spreadsheets."],["Owner overview","Revenue, margin, staff and approvals on one screen."]],flow:["Order created","Branch assigned","Team notified","Stock updated","Owner informed"],form:"Build your operating system",formText:"Describe your branches, processes and the decisions you need to see faster."},
    ru:{tag:"Облачная система для сети филиалов",title:"Все филиалы. Одна живая картина.",text:"Заказы, склад, команды и решения объединены в одном центре управления растущим бизнесом.",cta:"Изучить систему",section:"Операционный слой для всей сети",sectionText:"Владелец видит компанию целиком. Менеджер — свой филиал. Команда — только то, что требует действия сейчас.",metrics:[["24","активных филиала"],["8 347","заказов за месяц"],["12,6%","рост выручки"]],modules:[["Живые операции","Заказы, статусы и нагрузка филиалов в реальном времени."],["Управление филиалами","Разные права, цели и показатели каждой точки."],["Складские уведомления","Критические остатки и перемещения без таблиц."],["Обзор владельца","Выручка, маржа, команда и согласования на одном экране."]],flow:["Создан заказ","Выбран филиал","Команда уведомлена","Склад обновлён","Владелец видит результат"],form:"Создайте свою операционную систему",formText:"Опишите филиалы, процессы и решения, которые нужно принимать быстрее."},
  },
  inventory: {
    brand:"STOCKFLOW", route:"inventory-platform-demo", image:"/images/stk-lab/business-platforms/demos/stockflow-inventory.png", bg:"#f1eee7", ink:"#171717", accent:"#ff6b00", soft:"#ded8cd", radius:"rounded-none",
    en:{tag:"Inventory · purchasing · logistics",title:"Nothing lost between demand and delivery.",text:"A precise industrial platform for warehouses, suppliers, purchase orders, transfers and every unit in motion.",cta:"Trace the flow",section:"Control starts with traceability",sectionText:"From the first purchase request to the final branch receipt, every action has an owner, time and status.",metrics:[["2,450","tracked SKUs"],["98.4%","stock accuracy"],["−31%","urgent purchases"]],modules:[["Warehouse map","Locations, zones, bins and available quantities."],["Purchase orders","Requests, approvals, suppliers and expected delivery."],["Transfers","Dispatch and receipt between warehouses and branches."],["Supplier score","Delivery accuracy, quality and price history."]],flow:["Demand detected","PO approved","Supplier confirmed","Goods received","Branch replenished"],form:"Map your supply chain",formText:"Tell us how goods move today and where control is being lost."},
    ru:{tag:"Склад · закупки · логистика",title:"Ничего не теряется между спросом и поставкой.",text:"Точная индустриальная платформа для складов, поставщиков, закупок, перемещений и каждой единицы товара.",cta:"Проследить движение",section:"Контроль начинается с прослеживаемости",sectionText:"От первой заявки на закупку до приёмки в филиале каждое действие имеет ответственного, время и статус.",metrics:[["2 450","товарных позиций"],["98,4%","точность остатков"],["−31%","срочных закупок"]],modules:[["Карта склада","Зоны, ячейки и доступное количество товара."],["Закупки","Заявки, согласования, поставщики и ожидаемые поставки."],["Перемещения","Отправка и приёмка между складами и филиалами."],["Рейтинг поставщиков","Сроки, качество и история цен."]],flow:["Обнаружена потребность","Закупка одобрена","Поставщик подтвердил","Товар принят","Филиал пополнен"],form:"Опишите свою цепочку поставок",formText:"Расскажите, как движется товар и на каком этапе теряется контроль."},
  },
  workforce: {
    brand:"PULSE PEOPLE", route:"workforce-platform-demo", image:"/images/stk-lab/business-platforms/demos/pulse-workforce.png", bg:"#fff8f5", ink:"#342044", accent:"#ff7668", soft:"#eee5ff", radius:"rounded-[2.5rem]",
    en:{tag:"Workforce experience platform",title:"Work works better when people can see the plan.",text:"A friendly system for schedules, attendance, leave, payroll and everyday communication between employees and managers.",cta:"Meet the platform",section:"Clarity for every role",sectionText:"Employees get a simple personal space while managers connect staffing decisions to actual hours and payroll.",metrics:[["248","team members"],["94%","shifts confirmed"],["7 hrs","saved weekly"]],modules:[["Smart schedules","Build shifts and resolve gaps before they become problems."],["Attendance","Clock-ins, late arrivals and actual hours in one record."],["Leave requests","A clear request and approval flow for every employee."],["Payroll ready","Approved hours, overtime and payment status connected."]],flow:["Shift published","Employee confirms","Attendance captured","Hours approved","Payroll prepared"],form:"Give your team one clear place",formText:"Tell us how schedules, attendance and payroll work in your company."},
    ru:{tag:"Платформа управления командой",title:"Работать проще, когда каждый видит план.",text:"Дружелюбная система для графиков, посещаемости, отпусков, зарплат и ежедневного общения сотрудников с менеджерами.",cta:"Познакомиться с платформой",section:"Понятно для каждой роли",sectionText:"Сотрудник получает простой личный кабинет, а менеджер связывает графики с фактическими часами и расчётом зарплаты.",metrics:[["248","сотрудников"],["94%","смен подтверждено"],["7 часов","экономии в неделю"]],modules:[["Умные графики","Составляйте смены и закрывайте пробелы заранее."],["Посещаемость","Приходы, опоздания и фактические часы в одной записи."],["Отпуска","Понятная заявка и согласование для каждого сотрудника."],["Готово к зарплате","Подтверждённые часы, переработки и статусы выплат связаны."]],flow:["График опубликован","Сотрудник подтвердил","Время зафиксировано","Часы одобрены","Зарплата рассчитана"],form:"Дайте команде одно понятное место",formText:"Расскажите, как устроены графики, посещаемость и зарплаты."},
  },
  finance: {
    brand:"LEDGER / PRIVATE", route:"finance-platform-demo", image:"/images/stk-lab/business-platforms/demos/ledger-finance.png", bg:"#071712", ink:"#f0eadb", accent:"#cbaa67", soft:"#0d241c", radius:"rounded-sm",
    en:{tag:"Executive financial intelligence",title:"Know the profit behind every decision.",text:"A private analytics environment for cash flow, margins, forecasts, approvals and performance across the company.",cta:"Enter the overview",section:"Numbers with operational context",sectionText:"Revenue alone is not the answer. Connect sales, COGS, expenses and payroll to see what the business actually earns.",metrics:[["18.6%","net margin"],["$48.7M","operating cash flow"],["6 mo","rolling forecast"]],modules:[["Profitability","Gross and net profit by branch, product and period."],["Cash flow","Actual movement, obligations and forward-looking position."],["Forecasts","Scenario planning connected to real operating data."],["Approvals","Budgets, purchases and contracts requiring a decision."]],flow:["Data consolidated","Costs attributed","Margins calculated","Forecast updated","Decision approved"],form:"Design your executive view",formText:"Tell us which numbers you trust today and which decisions remain unclear."},
    ru:{tag:"Финансовая аналитика для владельца",title:"Знайте прибыль за каждым решением.",text:"Закрытая аналитическая среда для денежного потока, маржи, прогнозов, согласований и результатов всей компании.",cta:"Открыть обзор",section:"Цифры в контексте операций",sectionText:"Одной выручки недостаточно. Свяжите продажи, себестоимость, расходы и зарплаты, чтобы видеть реальный заработок бизнеса.",metrics:[["18,6%","чистая маржа"],["$48,7M","операционный cash flow"],["6 мес.","скользящий прогноз"]],modules:[["Прибыльность","Валовая и чистая прибыль по филиалам, продуктам и периодам."],["Денежный поток","Фактическое движение, обязательства и будущая позиция."],["Прогнозы","Сценарии, связанные с реальными операционными данными."],["Согласования","Бюджеты, закупки и договоры, ожидающие решения."]],flow:["Данные объединены","Расходы распределены","Маржа рассчитана","Прогноз обновлён","Решение принято"],form:"Создайте обзор для владельца",formText:"Расскажите, каким цифрам доверяете сегодня и какие решения остаются непрозрачными."},
  },
} as const;

export default function BusinessPlatformDemoPage({locale,kind}:{locale:Locale;kind:Kind}) {
  const p=platforms[kind], t=p[locale], other=locale==="ru"?"en":"ru";
  const industrial=kind==="inventory", friendly=kind==="workforce", finance=kind==="finance";
  return <main className="min-h-screen" style={{background:p.bg,color:p.ink}}>
    <div className="flex flex-wrap justify-center gap-x-5 gap-y-1 border-b px-4 py-2 text-center text-[10px] uppercase tracking-[.2em] opacity-70" style={{borderColor:`${p.ink}22`}}><span>{locale==="ru"?"Демо бизнес-платформы · STK Lab":"Business platform demo · STK Lab"}</span><Link href={`/${locale}/industries/business-platforms`}>{locale==="ru"?"Все платформы":"All platforms"} →</Link><Link href={`/${locale}/demo-admin`}>{locale==="ru"?"Демо-админка":"Demo admin"} →</Link></div>
    <header className="flex items-center justify-between border-b px-5 py-5 md:px-10" style={{borderColor:`${p.ink}22`}}><strong className={`${industrial?"font-mono":""} text-lg tracking-[.15em]`}>{p.brand}</strong><nav className="hidden gap-8 text-sm md:flex"><a href="#platform">{locale==="ru"?"Платформа":"Platform"}</a><a href="#modules">{locale==="ru"?"Модули":"Modules"}</a><a href="#contact">{locale==="ru"?"Запрос":"Request"}</a></nav><Link href={`/${other}/${p.route}`} className="border px-4 py-2 text-xs uppercase" style={{borderColor:`${p.ink}44`,borderRadius:friendly?"999px":"4px"}}>{other}</Link></header>
    <section className="relative min-h-[760px] overflow-hidden bg-cover bg-center" style={{backgroundImage:`linear-gradient(90deg, ${kind==="operations"?"rgba(4,15,38,.96)":finance?"rgba(4,17,13,.86)":industrial?"rgba(18,18,18,.78)":"rgba(52,32,68,.62)"} 0%, rgba(0,0,0,.16) 62%, rgba(0,0,0,.02) 100%), url(${p.image})`}}><div className="mx-auto flex min-h-[760px] max-w-7xl items-end px-5 pb-16 text-white md:px-10 md:pb-24"><div className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.3em]" style={{color:p.accent}}>{t.tag}</p><h1 className={`${industrial?"font-mono uppercase":friendly?"font-serif":""} mt-7 text-6xl font-semibold leading-[.9] tracking-[-.055em] md:text-8xl lg:text-[7rem]`}>{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70 md:text-xl">{t.text}</p><a href="#platform" className={`${p.radius} mt-9 inline-flex px-7 py-4 font-semibold`} style={{background:p.accent,color:finance?"#071712":industrial?"#171717":"white"}}>{t.cta} →</a></div></div></section>
    <section id="platform" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 md:grid-cols-[1.1fr_.9fr] md:px-10 md:py-32"><div><p className="text-xs uppercase tracking-[.28em] opacity-45">01 / Overview</p><h2 className={`${industrial?"font-mono uppercase":friendly?"font-serif":""} mt-5 text-5xl font-semibold tracking-[-.05em] md:text-7xl`}>{t.section}</h2><p className="mt-7 max-w-2xl text-xl leading-9 opacity-65">{t.sectionText}</p></div><div className="grid grid-cols-3 self-end border-y py-8" style={{borderColor:`${p.ink}33`}}>{t.metrics.map(([n,l])=><div key={l} className="px-2 text-center"><strong className="text-2xl md:text-4xl" style={{color:p.accent}}>{n}</strong><p className="mt-2 text-xs leading-5 opacity-50">{l}</p></div>)}</div></section>
    <section id="modules" className="px-5 py-24 md:px-10 md:py-32" style={{background:p.soft}}><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.28em] opacity-45">02 / Modules</p><div className="mt-12 grid gap-5 md:grid-cols-2">{t.modules.map(([name,text],i)=><article key={name} className={`${p.radius} border p-7 md:p-9`} style={{borderColor:`${p.ink}28`,background:`${p.bg}aa`}}><span className="text-xs opacity-35">0{i+1}</span><h3 className={`${industrial?"font-mono uppercase":friendly?"font-serif":""} mt-12 text-3xl font-semibold`}>{name}</h3><p className="mt-4 max-w-lg leading-7 opacity-60">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32"><p className="text-xs uppercase tracking-[.28em] opacity-45">03 / Workflow</p><h2 className={`${industrial?"font-mono uppercase":friendly?"font-serif":""} mt-5 text-5xl font-semibold tracking-[-.05em] md:text-7xl`}>{locale==="ru"?"Один непрерывный процесс":"One continuous workflow"}</h2><div className="mt-14 grid gap-3 md:grid-cols-5">{t.flow.map((step,i)=><div key={step} className={`${p.radius} border p-5`} style={{borderColor:`${p.ink}28`}}><span className="text-xs" style={{color:p.accent}}>0{i+1}</span><p className="mt-8 font-semibold">{step}</p></div>)}</div></section>
    <section id="contact" className="px-5 py-24 text-white md:px-10 md:py-32" style={{background:finance?"#020806":kind==="operations"?"#030b19":industrial?"#171717":"#342044"}}><div className="mx-auto max-w-5xl text-center"><p className="text-xs uppercase tracking-[.28em] text-white/40">04 / Request</p><h2 className={`${industrial?"font-mono uppercase":friendly?"font-serif":""} mt-5 text-5xl font-semibold tracking-[-.05em] md:text-7xl`}>{t.form}</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/60">{t.formText}</p><DemoSiteOrderForm locale={locale} siteName={`${p.brand} — business platform`} kind="business" /></div></section>
    <footer className="flex flex-col gap-2 px-5 py-8 text-xs opacity-55 md:flex-row md:justify-between md:px-10"><span>© 2026 {p.brand}</span><span>{locale==="ru"?"Демонстрационная платформа STK Lab":"A demonstration platform by STK Lab"}</span></footer>
  </main>;
}
