import Image from "next/image";
import Link from "next/link";
import DemoSiteOrderForm from "./DemoSiteOrderForm";

type Locale="ru"|"en";
type Kind="barber"|"events"|"animators"|"kids";

const data={
  barber:{brand:"IRONWOOD",hero:"/images/stk-lab/beauty/demos/ironwood-barbershop-hero-v1.webp",bg:"#11100f",ink:"#f2eadb",accent:"#b78950",route:"ironwood-barbershop-demo",
    en:{label:"Barbershop · craft since 2016",title:"Good cuts. Better rituals.",text:"A neighbourhood barbershop for precise cuts, hot towels and conversations worth staying for.",cta:"Book a chair",section:"The chair is yours",story:"Built by two brothers who wanted the kind of place their father took them to: no rush, honest advice and a proper coffee.",services:[["Signature cut","45 min · $38"],["Cut & beard","75 min · $58"],["Traditional shave","45 min · $42"],["Father & son","80 min · $64"]],feature:"Your barber remembers the details.",featureText:"Preferred length, last formula and every appointment stay in your profile."},
    ru:{label:"Барбершоп · ремесло с 2016",title:"Точный стиль. Правильный ритуал.",text:"Барбершоп по соседству: точные стрижки, горячее полотенце и разговоры, ради которых не хочется спешить.",cta:"Выбрать кресло",section:"Это кресло — ваше",story:"Два брата создали место, куда их когда-то приводил отец: без спешки, с честным советом и правильным кофе.",services:[["Фирменная стрижка","45 мин · $38"],["Стрижка и борода","75 мин · $58"],["Классическое бритьё","45 мин · $42"],["Отец и сын","80 мин · $64"]],feature:"Ваш барбер помнит детали.",featureText:"Любимая длина, предыдущая форма и история визитов сохраняются в профиле."}},
  events:{brand:"VELVET STAGE",hero:"/images/stk-lab/entertainment/velvet-stage-hero-v1.webp",bg:"#150b0d",ink:"#f8eee4",accent:"#d4a357",route:"velvet-stage-events-demo",
    en:{label:"Wedding · show · private celebration",title:"We produce the moment everyone remembers.",text:"From the first entrance to the final light cue — a complete celebration shaped as one living performance.",cta:"Create our event",section:"Not a package. A narrative.",story:"The studio began backstage. That is why every wedding, anniversary and brand evening is built with the timing of a show and the warmth of a private gathering.",services:[["Wedding production","Concept to final dance"],["Original show","Artists, stage and direction"],["Private celebration","Intimate and personal"],["Brand event","A story guests can feel"]],feature:"One evening. Hundreds of invisible cues.",featureText:"Direction, scenography, artists, sound, light, timing and guest care work as one production."},
    ru:{label:"Свадьба · шоу · частный праздник",title:"Создаём момент, который помнят все.",text:"От первого выхода до финального света — цельный праздник, поставленный как живое представление.",cta:"Создать событие",section:"Не пакет. Ваша история.",story:"Студия началась за кулисами. Поэтому свадьбы, юбилеи и бренд-вечера строятся с точностью шоу и теплом личного праздника.",services:[["Свадьба под ключ","От идеи до финального танца"],["Авторское шоу","Артисты, сцена и режиссура"],["Частный праздник","Камерно и лично"],["Бренд-событие","История, которую чувствуют"]],feature:"Один вечер. Сотни незаметных сигналов.",featureText:"Режиссура, сценография, артисты, звук, свет, тайминг и забота о гостях работают как единое целое."}},
  animators:{brand:"SPARK!",hero:"/images/stk-lab/entertainment/spark-animators-hero-v1.webp",bg:"#fff8ed",ink:"#44246b",accent:"#ff6c59",route:"spark-animators-demo",
    en:{label:"Children's parties · real play",title:"No awkward scripts. Just a room full of joy.",text:"Warm, talented performers who notice every child and turn the party into a shared adventure.",cta:"Choose a program",section:"Play made personal",story:"Spark was founded by a theatre teacher who saw shy children disappear inside noisy party programs. Here every child gets a role, never pressure.",services:[["Bubble laboratory","3–7 years"],["Little detectives","6–10 years"],["Creative party","4–12 years"],["Family game show","Children + adults"]],feature:"We learn the birthday child before the party.",featureText:"Interests, temperament, favourite games and the guest mix shape the program."},
    ru:{label:"Детские праздники · настоящая игра",title:"Без заученных криков. Только радость.",text:"Тёплые профессиональные аниматоры замечают каждого ребёнка и превращают праздник в общее приключение.",cta:"Выбрать программу",section:"Игра с характером ребёнка",story:"Spark создала театральный педагог, заметившая, как застенчивые дети теряются в шумных программах. Здесь у каждого есть роль, но нет давления.",services:[["Лаборатория пузырей","3–7 лет"],["Маленькие детективы","6–10 лет"],["Творческая вечеринка","4–12 лет"],["Семейное шоу","Дети + взрослые"]],feature:"До праздника мы узнаём именинника.",featureText:"Интересы, характер, любимые игры и состав гостей формируют программу."}},
  kids:{brand:"WONDERNEST",hero:"/images/stk-lab/entertainment/wondernest-kids-hero-v1.webp",bg:"#fff6e9",ink:"#254e49",accent:"#ef765e",route:"wondernest-kids-demo",
    en:{label:"Play centre · birthdays · family café",title:"A little world built for big days.",text:"Climb, invent, slide, celebrate — a beautiful indoor play space where children lead the day and adults can breathe.",cta:"Plan a birthday",section:"More than a playroom",story:"Created by a mother and an architect after too many birthdays where children loved the playground but parents had nowhere comfortable to sit.",services:[["Soft play city","2–8 years"],["Climbing garden","4–12 years"],["Creative atelier","Daily workshops"],["Birthday rooms","Private celebrations"]],feature:"One place for play and the whole birthday.",featureText:"Host, decorations, child-friendly menu, cake moment, private room and play access are coordinated together."},
    ru:{label:"Игровой центр · дни рождения · семейное кафе",title:"Маленький мир для больших дней.",text:"Лазать, придумывать, скользить и праздновать — красивое пространство, где дети ведут день, а взрослые могут выдохнуть.",cta:"Спланировать день рождения",section:"Больше, чем игровая",story:"Центр придумали мама и архитектор после множества праздников, где детям нравились горки, а взрослым негде было спокойно посидеть.",services:[["Мягкий игровой город","2–8 лет"],["Сад для лазания","4–12 лет"],["Творческое ателье","Мастер-классы каждый день"],["Комнаты праздников","Закрытые дни рождения"]],feature:"В одном месте — игра и весь праздник.",featureText:"Ведущий, декор, детское меню, вынос торта, отдельная комната и игровое время согласованы вместе."}},
} as const;

export default function ExperienceDemoPage({locale,kind}:{locale:Locale;kind:Kind}){
 const d=data[kind],t=d[locale],other=locale==="ru"?"en":"ru"; const playful=kind==="animators"||kind==="kids";
 return <main style={{background:d.bg,color:d.ink}} className="min-h-screen">
  <header className="flex items-center justify-between border-b px-5 py-5 md:px-10" style={{borderColor:`${d.ink}30`}}><strong className={`${kind==="events"?"font-serif":playful?"text-2xl":"tracking-[.2em]"}`}>{d.brand}</strong><nav className="hidden gap-8 text-sm md:flex"><a href="#story">{locale==="ru"?"История":"Story"}</a><a href="#services">{locale==="ru"?"Программы":"Services"}</a><a href="#book">{locale==="ru"?"Заявка":"Enquire"}</a></nav><Link href={`/${other}/${d.route}`} className="rounded-full border px-4 py-2 text-xs uppercase" style={{borderColor:`${d.ink}50`}}>{other}</Link></header>
  <section className={`relative mx-3 mt-3 min-h-[760px] overflow-hidden ${kind==="barber"?"rounded-sm":kind==="events"?"rounded-t-[8rem]":kind==="animators"?"rounded-[4rem_10rem_4rem_10rem]":"rounded-[3rem]"}`}><Image src={d.hero} alt={d.brand} fill priority className="object-cover" sizes="100vw"/><div className={`absolute inset-0 ${playful?"bg-gradient-to-r from-white/85 via-white/15 to-transparent":"bg-gradient-to-r from-black/80 via-black/25 to-transparent"}`}/><div className={`relative flex min-h-[760px] max-w-7xl items-center px-7 md:px-14 ${playful?"":"text-white"}`}><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:d.accent}}>{t.label}</p><h1 className={`${kind==="events"?"font-serif italic":kind==="barber"?"uppercase":""} mt-6 text-6xl leading-[.88] tracking-[-.06em] md:text-8xl`}>{t.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 opacity-75">{t.text}</p><a href="#book" className={`mt-9 inline-flex px-7 py-4 font-semibold ${playful?"rounded-full":"border"}`} style={{background:playful?d.accent:"transparent",borderColor:d.accent,color:playful?"#fff":d.accent}}>{t.cta} →</a></div></div></section>
  <section id="story" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 md:grid-cols-2 md:px-10 md:py-32"><h2 className={`${kind==="events"?"font-serif italic":""} text-5xl leading-[.95] md:text-7xl`}>{t.section}</h2><p className="self-end text-xl leading-9 opacity-65">{t.story}</p></section>
  <section id="services" className="px-5 py-24 md:px-10 md:py-32" style={{background:kind==="barber"?"#1b1917":kind==="events"?"#2a1116":kind==="animators"?"#efe1ff":"#dcefe7",color:kind==="barber"||kind==="events"?"#f8eee4":d.ink}}><div className="mx-auto max-w-7xl"><div className={`grid gap-4 ${playful?"md:grid-cols-2":"md:grid-cols-4"}`}>{t.services.map(([name,meta],i)=><article key={name} className={`${kind==="animators"?"rounded-[5rem_2rem]":kind==="kids"?"rounded-[2rem]":"border"} min-h-60 p-7`} style={{borderColor:`${d.accent}66`,background:playful?(i%2?"#ffffff90":d.accent+"22"):undefined}}><span className="text-xs opacity-45">0{i+1}</span><h3 className="mt-20 text-3xl">{name}</h3><p className="mt-3 opacity-60">{meta}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-24 text-center md:py-36"><p className="text-xs uppercase tracking-[.25em]" style={{color:d.accent}}>{locale==="ru"?"Наш подход":"Our approach"}</p><h2 className="mx-auto mt-6 max-w-5xl text-5xl leading-[.95] md:text-7xl">{t.feature}</h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 opacity-60">{t.featureText}</p></section>
  <section id="book" className="px-5 py-24 text-white md:px-10 md:py-32" style={{background:kind==="animators"?"#44246b":kind==="kids"?"#254e49":"#090909"}}><div className="mx-auto max-w-5xl text-center"><h2 className="text-5xl md:text-7xl">{t.cta}</h2><DemoSiteOrderForm locale={locale} siteName={`${d.brand} — enquiry`} kind={kind==="barber"?"beauty":"business"}/></div></section>
  <footer className="flex flex-col gap-3 px-5 py-8 text-xs opacity-55 md:flex-row md:justify-between md:px-10"><span>© 2026 {d.brand}</span><Link href={`/${locale}/${kind==="barber"?"industries/beauty":"industries/entertainment"}`}>{locale==="ru"?"Все проекты Tafa Lab":"All Tafa Lab projects"} →</Link></footer>
 </main>
}
